### ISSUE TITLE
[改善]パスワードリセット機能が動作するようにする

### ISSUE THREAD

**Issue by h-yoshikawa44** [h-yoshikawa44/ooui-memo#22]
## 対象環境
開発

## 目的
パスワードリセット機能が動作するように、メール送信設定をする

## 作業内容
- Docker 環境にメール送信クライアントを追加
- 必要なメール送信を設定する
- 画面遷移図の修正（#20 で対応見送りしてた分）

**Comment by h-yoshikawa44** [comment]
## メール設定
参考：[Docker × Laravel メールの送信処理をローカルで確認する](https://qiita.com/ucan-lab/items/49e7f4986564f68e95c4)

docker-compose.yml にコンテナ追加
```yml
mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
```

.env を修正
```
MAIL_HOST=mail
MAIL_PORT=1025
MAIL_FROM_ADDRESS=ooui-memo@example.com
```
ポートが1025なのは、MailHog の SMTP がデフォルトで待ち受けているのが 1025 だから。
