### ISSUE TITLE
[改善]CI/CD設定

### ISSUE THREAD

**Issue by h-yoshikawa44** [h-yoshikawa44/ooui-memo#27]
## 対象環境
開発、本番

## 目的
Linter、テストの自動化、自動デプロイのフロー確立

## 作業内容
- GitHub Actions で Linter、テストの自動化
- Heroku と連携させて自動デプロイにする

**Comment by h-yoshikawa44** [comment]
## PHPCS の設定
#15 の時点で設定ファイルを作成していなかったので作成
参考：[LaravelにPHP_CodeSnifferを導入しコーディング規約（PSR）に沿った記述を行う](https://www.ritolab.com/entry/188)

```xml
<?xml version="1.0"?>
<ruleset name="PSR2/Laravel">
    <description>PSR2 compliant rules and settings for Laravel</description>

    <arg name="extensions" value="php" />

    <!-- 適用コーディング規約の指定 -->
    <rule ref="PSR2" />

    <!-- 出力に色を適用 -->
    <arg name="colors" />

    <!-- オプション p:進捗表示  s:エラー表示時にルールを表示 -->
    <arg value="ps" />

    <!-- 除外ディレクトリ -->
    <exclude-pattern>/bootstrap/</exclude-pattern>
    <exclude-pattern>/config/</exclude-pattern>
    <exclude-pattern>/database/</exclude-pattern>
    <exclude-pattern>/node_modules/</exclude-pattern>
    <exclude-pattern>/public/</exclude-pattern>
    <exclude-pattern>/resources/</exclude-pattern>
    <exclude-pattern>/routes/</exclude-pattern>
    <exclude-pattern>/storage/</exclude-pattern>
    <exclude-pattern>/vendor/</exclude-pattern>
    <exclude-pattern>/server.php</exclude-pattern>
    <exclude-pattern>/app/Console/Kernel.php</exclude-pattern>
    <exclude-pattern>/tests/CreatesApplication.php</exclude-pattern>
</ruleset>
```
実行コマンド
```
$ ./vendor/bin/phpcs --standard=phpcs.xml .
```

**Comment by h-yoshikawa44** [comment]
## GitHub Actions で使用する PHP のバージョン指定
現時点でデフォルトが8系になっている。
そのため、composer でライブラリをインストールする時に、lock ファイルとの整合性確認に失敗していた。

```
$ composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

Your lock file does not contain a compatible set of packages. Please run composer update.
```

明示的に 7.4 系を使うようにして対応
参考：[GitHub Actions で PHP のバージョンを指定する](https://zenn.dev/306/articles/e71ba4c8b2dcfa)
```yml
# GitHub Actions の PHP のデフォルトが 8系のため 7.4を使うように指定
 - name: Setup PHP 7.4
   run: sudo update-alternatives --set php /usr/bin/php7.4
```

**Comment by h-yoshikawa44** [comment]
## Heroku へ自動デプロイ
Heroku のダッシュボードから連携する。
deploy → GitHub アカウントを認証 → リポジトリ選択 → 
Wait for CI to pass before deploy にチェックを入れて、Automatic deploys を有効化

※この自動デプロイでは、サブディレクトリの指定ができないっぽい。
別途 GitHub Actions で対応したほうがよさそう。

[GitHub Actions で Heroku に自動デプロイ](https://zenn.dev/shin_shin_01/articles/53009a81728e21)

**Comment by h-yoshikawa44** [comment]
## GitHub Actions によるデプロイ

### Heroku へのデプロイ
デプロイできるアクションを使った。
secrets も併せて設定
```yml
  - uses: akhileshns/heroku-deploy@v3.12.12
       with:
         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
         heroku_app_name: ${{ secrets.HEROKU_API_NAME }}
         heroku_email: ${{ secrets.HEROKU_EMAIL }}
         appdir: src
```

### Slack 通知
```yml
  - name: Slack Notification
    uses: 8398a7/action-slack@v3
    if: always()
    with:
      status: ${{ job.status }}
      fields: repo,message,commit,author,action,eventName,ref,workflow
      author_name: 'deploy'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
